checks:
  php:
    code_rating: true
    duplication: true
    
filter:
  paths:
    - src/*
    - recipe/*
    - bin/*

build:
  dependencies:
    before:
      - sudo apt-get update -qq 
      - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
      - pecl install -f ssh2-beta < test/.noninteractive
      - php -m | grep ssh2
  tests:
    override:
      -
        command: phpunit --coverage-clover=coverage
        coverage:
          file: coverage
          format: php-clover
