language: php

sudo: required

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"

install:
  - eval `ssh-agent -s`
  - test/travis/setup-secure-shell.sh
  - composer self-update
  - composer update --no-interaction --prefer-source $COMPOSER_FLAGS

script:
  - phpunit

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3ffa605389816ec39774
    on_success: change
    on_failure: always
    on_start: never
